name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Package Linux and publish
        run: npx electron-builder -l -p always
      - uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: dist/*

  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Package Windows and publish
        run: npx electron-builder -w -p always
      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/*
